services:
  xmcp-server:
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: bun run src/server.ts
    networks:
      - xmcp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3001}/health"]
      interval: 3s
      timeout: 5s
      retries: 3

  mcp-inspector:
    build:
      context: inspector
    environment:
      HOST: 0.0.0.0
    ports:
      - 6274:6274
      - 6277:6277
    volumes:
      - ./inspector:/app
      - /app/node_modules
    working_dir: /app
    command: bun run inspect
    networks:
      - xmcp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6277/health"]
      interval: 3s
      timeout: 5s
      retries: 3
    depends_on:
      xmcp-server:
        condition: service_healthy

networks:
  xmcp:
    driver: bridge
