services:
  xmcp-server:
    build:
      context: .
      target: dev
    env_file:
      - .env
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: bun run src/server.ts
    networks:
      - xmcp

  mcp-inspector:
    image: node:24-alpine3.21
    environment:
      HOST: 0.0.0.0
    ports:
      - 6274:6274
      - 6277:6277
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npx @modelcontextprotocol/inspector node src/server.ts
    networks:
      - xmcp

networks:
  xmcp:
    driver: bridge
